services:
  # Backend API service
  - type: web
    name: ai-document-reader-api
    env: python
    region: oregon # Choose the region closest to your users
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false # This means you'll provide this value in the Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true # Render will generate a random value for this
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: SERVER_PORT
        fromService:
          type: web
          name: ai-document-reader-api
          envVarKey: PORT

  # Frontend static site
  - type: web
    name: ai-document-reader-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ai-document-reader-api
          property: url